version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    expose:
      - "27017"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/subscriptions-docker
  subscriptions:
    container_name: subscriptions
    build: .
    image: newsletter/subscription-service:0.0.1
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 5m
      timeout: 10s
      retries: 3

      